name = "Dawn Hugo"
license = "GPLv3"
licenselink = "https://github.com/pitscher/dawn-hugo/blob/main/LICENSE"
description = "The Hugo version of the Dawn theme for the Ghost CMS"
homepage = "https://github.com/pitscher/dawn-hugo"
tags = ["blog", "ghost", "dark", "light"]
features = ["Indication of article reading time", "light and dark mode", "mobile-ready"]
min_version = "0.54.0"

# This theme supports multiple authors - configure their metadata here
authors = [
  {name = "Name of the author", homepage = "Website of the author"},
  {name = "Name of the author", homepage = "Website of the author"}
]

[author]
  name = "Pitscher"
  homepage = "https://github.com/pitscher"

[original]
  name = "Dawn"
  homepage = "https://github.com/TryGhost"
  repo = "https://github.com/TryGhost/Dawn"
